abstract class LastTransactionCubitState {}

class InitializeLastTransactionCubit extends LastTransactionCubitState{}

class LastTransactionLoadingState extends LastTransactionCubitState{}

class LastTransactionSuccessState extends LastTransactionCubitState{}
class LastTransactionErrorState extends LastTransactionCubitState{}